# Generated by Django 3.0.8 on 2020-08-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200811_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderManager',
        ),
    ]
